AlaskaAirlines/auro-input

docs/api.md
src/base-input.js

**Fixes:** #2
Adds a custom event when triggering a clear function on the input value. 

feat: add custom event for clearing input value

---

.npmignore
README.md
index.html
package-lock.json
package.json
polymer.json
src/auro-input.js
src/base-input.js
test/auro-input.test.js

Fixes #17
This PR sets the `aria-invalid` attribute on the input to better communicate to assistive tech whether the input is invalid. This prevents the input being detected as invalid when first focusing the input for some screen reader/browser combinations (Chrome/NVDA, cc [this Paciello Group article](https://developer.paciellogroup.com/blog/2019/02/required-attribute-requirements/)). 
Unfortunately, this doesn't fix Firefox/NVDA. There's an [ancient open Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=666544) around the invalid state on first blur. To work around this issue, we'd have to stop using the HTML5 required attribute and validation and I don't think that's worth the effort right now.
Other small fixes:
- set ID on error message to link to input field with …

Improve invalid state and description for assistive tech

---

docs/api.md
src/base-input.js

**Fixes:** #41 
This PR will catch the DOMException thrown from the support feature related to #6 

auro-input: catch exception 

---

src/style.scss

**Fixes:** #34 
Update color and size of label font to match Figma documentation

Jbaker/label styles/#34

---

src/base-input.js

**Fixes:** #26
This change adds a string replace on the inputElement value that strips all non-numeric characters that is triggered on input change. 
This change has been tested for typing each character individually as well as pasting in a value with and without non-numeric values.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a …

fix(pattern): improve non-numeric restriction for CC numbers

---

README.md
demo/demo.md
demo/index.html
package.json
src/auro-input.js
src/style.scss

**Fixes:** #36 
This change refactors the way credit card icons are implemented in an effort to minimize the bundle size.
The new version has a peer dependency on `auro-icon` and dynamically includes that correct icon HTML in the template as the input value changes.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the …

auro-input: refactor templating of icons for CC format

---

src/auro-input.js

**Fixes:** #36
This change implements an alternative templating solution provided by @geoffrich here: #48 (comment).

Jbaker/simpler icon template/#48

---

src/style.scss

**Fixes:** #99 
This update addresses this issue to meet the design spec.
BEFORE: 
#AFTER   
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter …

Add white background to bordered type #99

---

docs/design-notes.md
docs/figma.md

Added design release notes.
**Fixes:** #101 

docs: added design notes for new date format input

---

demo/demo.md
docs/api.md
package-lock.json
src/auro-input.js
src/base-input.js
src/style.scss
test/auro-input.test.js

Support MM/YYYY format in "date" input fields
**Resolves:** #115 

Add support for MM/YYYY

---

demo/demo.md
src/auro-input.js
src/base-input.js
test/auro-input.test.js

**Resolves:** #112 #113 
The scope of this update adds the new feature to support corp credit cards with less than 16 digits and a new `27` numeration for the Alaska card icon. 
This PR also refactors the use of the regex per credit card supported. 
_Pull Requests will be evaluated by their …

Support commercial cards

---

demo/demo.md
demo/index.html
demo/util.js
docs/api.md
src/auro-input.js
src/base-input.js
src/i18n.js
test/auro-input.test.js

**Resolves:** #103 
_Please summarize the scope of the changes you have submitted, what the intent of the work is, and anything that describes the before/after state of the project._
The scope of this project is to introduce a new `lang` property at the element scope which will, on load, trigger the placement of predefined copy in the requested language. 
Current languages supported are `en` and `es`. 
Predefined strings and their localized versions were moved from being internal to the element to an external js file. While the current scope only supports `en` and `es`, additional languages can be supported with …

Add localized text support 

---

src/auro-input.js

**Resolves:** #57 
The scope of this update is to support additional attributes when type password is used. 
Before:
After: 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a …

Support no spellcheck for type password

---

src/auro-input.js
src/base-input.js

modified:   src/auro-input.js
modified:   src/base-input.js
**Resolves:** #114 
This commit will refactor the existing functionality to accept a string value versus setting the boolean to be only one type. 
_Pull Requests will be evaluated by their quality of update and …

Update to accept string versus boolean

---

demo/demo.md
src/base-input.js

modified:   demo/demo.md
modified:   src/base-input.js
**Resolves:** #47 
The scope of this update is to add support for `type="number"` that restricts the use of the keyboard entry types as well exposes the expected virtual keyboard on a mobile device. The scope of this update also exposes the `minlength` and `maxlength` attributes to the public API to allow users to restrict character length as needed. 
Please delete options that …

Add support for number input types

---

demo/demo.md
docs/api.md
src/auro-input.js
src/base-input.js
test/auro-input.test.js

**Fixes:** #122 
The scope of this pull request will refactor the pattern, spellcheck, autocorrect and autocapitolize attributes to be supported in the public API. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. …

Update to support the pattern attr in the public API

---

docs/api.md
src/auro-input.js
src/base-input.js

**Fixes:** #129
This adds the `parts` attribute to the various elements in auro-input so that the CSS can be customized from a parent component.
**Thank you for your …

feat(styling): support CSS Parts customization #129

---

demo/demo.md
docs/api.md
package-lock.json
package.json
src/base-input.js

modified:   demo/demo.md
modified:   src/base-input.js
modified:   docs/api.md
**Fixes:** #134 
The scope of this update exposes an internal property so that users can pre-set custom validation messages to be used with already supported validation and `required` features. 
This update also updates the name of the property to be more in line with the actual HTML specification for a similar feature.
API docs and demo files have been …

Expose api prop for setting custom message

---

demo/demo.md
docs/api.md
src/base-input.js
test/auro-input.test.js

modified:   demo/demo.md
modified:   src/base-input.js
modified:   test/auro-input.test.js
**Resolves:** #132 
The scope of this update introduces the new boolean attribute of `keyValidate` that enables a user to define the state of an input element as `invalid` with the initial interaction versus having to wait until a `blur` event to determine validity. 
**By submitting this Pull …

Enable real-time validation with key event

---

demo/demo.md
docs/api.md
src/base-input.js
test/auro-input.test.js

**Fixes:** #136 
The scope of this PR is to expand support for the use of `placeholder` to work on all inputs versus only the date type. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be …

Update placeholder support for all inputs 

---

src/base-input.js

**Fixes:** #142
This change adds logic to when we are adding the sticky class to the input label and also accounts for removing the sticky class when the input has an empty value.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your …

fix(label): remove sticky label class when input is empty #142

---

docs/api.md
package-lock.json
src/base-input.js

**Fixes:** #147
Add a new `ready` property and `notifyReadiness()` function. 
nofityReadiness() is called at a point when we understand all calculations necessary for the component to function properly.
At this point we set `ready` to true and sent `auroMenu-ready` as an event.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation …

feat(readiness): add readiness check and event notification #147

---

demo/numberFormat.html
demo/numberFormat.md

new file:   demo/numberFormat.html
new file:   demo/numberFormat.md
**Resolved:** #150
The scope of this update is to add documentation about how auro-input supports credit card and date number formatting. 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of …

Add support for number formatting

---

src/style.scss

Removed white text color that is visible on the default input field.
**Fixes:** #153

Junelee/bkg text color/#153

---

package-lock.json
package.json
src/base-input.js

**Fixes:** #166
Update to use the newer release of webcorestylesheets and remove focus-visible.

fix(imports): remove focus-visible import and dependency #166

---

src/base-input.js
test/auro-input.test.js

**Fixes:** #177
Emit 'input' event notification on all value changes not just typed and clear changes.

fix(event): fire input event when programmatically changing value #177

---

package-lock.json
src/base-input.js
test/auro-input.test.js

**Fixes:** #181 
When the user has a valid date in the datepicker input and then exclusively uses the keyboard to change the date, the cursor placed by the user now stays in place, rather than automatically moving to the end of the date input string.
_Pull Requests will be evaluated by their …

Fix auto cursor placement for keyboard input for datepicker

---

src/base-input.js

**Fixes:** #189
Reset this.errorMessage to undefined when the html5 input message is cleared out

fix(error): reset error message in event #189

---

src/base-input.js

**Fixes:** #196 
Now crawls shadow DOM to validate activeElement, used in validation workflow.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter …

Better active element assessment

---

src/style.scss

**Fixes:** #184 
Set the value of the min/max height of the input element to `58px`.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the …

Make height consistent with other form elements

---

src/base-input.js
src/style.scss

**Fixes:** #198 
Disabled HTML5 input mouse events when not directly hovered over `auro-input`. This fixes issue where clicking on content in a dropdown bib that was opened over another `auro-input` would register the click with the dropdown content, as well as silently register the HTML5 input click that was underneath (e.g. `HTML5input.addEventListener('click', ...)` would not detect the click, but otherwise behave as though it did).
Please delete options …

Improve hover event handling for HTML5 input

---

package-lock.json
src/style.scss

**Fixes:** #186, #187, #195
Ellipse the text of the label and input when the characters don't fit in the width of the `auro-input` element.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be …

Ellipse input and label text

---

apiExamples/value.js
demo/demo.md
demo/examples.js
src/base-input.js

**Fixes:** #191 
When `this.value = undefined`, the HTML5 input value resets.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the …

Better value reset handling

---

demo/demo.md
src/style.scss

**Fixes:** #106, #200 
* Converted CSS for the border of input to use `box-shadow` instead of `outline` so that the input border corners would be rounded on Safari.
* Made it so that all error states make the border/outline color of `auro-input` red.
_Pull Requests will be evaluated by their …

Improve UI for non required error states

---

src/style.scss

**Fixes:** #215 
Non-bordered `auro-input`s contained a halo around the entire element. Now bordered and non-bordered inputs use different values for the `box-shadow` css property.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of …

Fix non-bordered UI error

---

demo/demo.md

**Fixes:** #217
Add additional documentation to match the code in the demo code for the custom validity message.
-- Auro Design System …

docs(pattern): include validity attribute for pattern validation #217

---

src/style.scss

**Fixes:** #201 
Adjust the placement of the accent icon on non-bordered inputs to reflect the design blueprint.
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation …

Adjust placement of accent icon

---

docs/api.md
src/base-input.js

**Fixes:** #233
Docs defined an event that was never fired. This event now fires at the correct time.

fix(event): validation event defined in docs is fired #233

---

docs/api.md
src/base-input.js
test/auro-input.test.js

**Fixes:** #244 
Changes:
* Remove `focus` attribute from validation method
* Refactor validation
* Update tests to reflect JS changes
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be …

Delete focus attribute from validation

---

.npmignore
index.js
src/auro-input.js
test/auro-input.test.js

**Fixes:** #246
This PR follows the work done in other auro components where we implement the custom CE naming convention to allow for multiple versions of the same auro component to exist on the same page.
_Pull Requests will be evaluated by their quality of update and whether it is consistent …

Implement CE naming convention

---

package-lock.json
package.json

**Fixes:** #238 
Revert `cleave.js` package version to the previous release.
AC:
The link to the `cleave.js` release that we currently support is here: https://github.com/nosir/cleave.js/releases/tag/v1.6.0
_Pull Requests will be evaluated by their quality of update and whether it is consistent …

Revert cleave.js version

---

src/auro-input.js
src/base-input.js
web-test-runner.config.mjs

**Fixes:** #265, #267 
- Add `auro-input` attribute when element is using a custom tagname.
- remove all keyup event code that is no longer needed for positioning the label. …

Element Tagging and keyup event removal

---

demo/demo.md

**Fixes:** #273 
Update the "Validate On Input" example to use the correct attribute for the help text message when an error occurs
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered …

Fix for validate on input example

---

.github/ISSUE_TEMPLATE/bug_report.yml
README.md
demo/index.html
demo/numberFormat.html
demo/numberFormat.md
package-lock.json

**Resolves:** # (issue, if applicable)
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require …

perf: alaskaairux ref updates

---

docs/api.md
src/base-input.js

**Resolves:** #305 
_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your …

Remove private property from API docs

---

package-lock.json
package.json
scripts/version.mjs
src/auro-input.js
src/buttonVersion.js
src/styles/notificationIcons.scss
test/auro-input.test.js

Updates the component to use the latest version of auro-button that gives us a flat variant appropriate for use and theme supported for the clear (x) and showpassword buttons. …

perf(button): use new auro-button flat variant for clear and show password

---

package-lock.json
package.json
src/buttonVersion.js
src/iconVersion.js

Update to use the correct dependency versions

perf(deps): use updated dependency versions

---

package-lock.json
package.json
src/auro-input.js
src/buttonVersion.js

perf(deps): update to latest beta dependencies

---

package-lock.json
package.json

perf: revert auro-library version
